// const data = [
//   {
//     // id: "name",
//     // name: "name",
//     // type: "text",
//     // placeholder: "e.g. Jane Appleseed",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     // id: "card-number",
//     // name: "card-number",
//     // type: "text",
//     // placeholder: "eg. 1234 5678 9123 0000",
//     // maxLength: "19",
//     // ariaLabel: "",
//     // inputMode: "numeric",
//     // pattern: "[0-9]*",
//   },
//   {
//     id: "month",
//     name: "month",
//     type: "text",
//     placeholder: "MM",
//     maxLength: "2",
//     ariaLabel: "Expiration month",
//     inputMode: "numeric",
//     pattern: "[0-9]*",
//   },
//   {
//     // id: "year",
//     name: "year",
//     type: "text",
//     placeholder: "YY",
//     maxLength: "2",
//     ariaLabel: "Expiration year",
//     inputMode: "numeric",
//     pattern: "[0-9]*",
//   },
//   {
//     // id: "cvc",
//     // name: "cvc",
//     // type: "text",
//     // placeholder: "e.g. 123",
//     // maxLength: "3",
//     // ariaLabel: "",
//     // inputMode: "numeric",
//     // pattern: "[0-9]*",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
//   {
//     id: "",
//     name: "",
//     type: "",
//     placeholder: "",
//     maxLength: "",
//     ariaLabel: "",
//     inputMode: "",
//     pattern: "",
//   },
// ];

// export default data;
